#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

docker run -it \
  --name=${PROJECT_NAME} \
  --device=/dev/i2c-1 \
  --volume ${PROJECT_ROOT}/src:/catkin_ws/src \
  --rm \
  ${PROJECT_NAME}
